[features]
seeds = false
[programs.devnet]
solana_twitter = "BxnMyazpxRDcr4wtX2ok7DXGEMfuo4Ssi5uWe8kcKTAe"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/robertkottelin/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
